// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using uFrame.IOC;
using uFrame.Kernel;
using uFrame.MVVM;
using uFrame.Serialization;


public class InitSceneBase : uFrame.Kernel.Scene {
    
    public override string DefaultKernelScene {
        get {
            return "GodBattleKernelScene";
        }
    }
    
    public virtual InitSceneSettings Settings {
        get {
            return _SettingsObject as InitSceneSettings;
        }
        set {
            _SettingsObject = value;
        }
    }
}

public class InitSceneLoaderBase : SceneLoader<InitScene> {
    
    protected override IEnumerator LoadScene(InitScene scene, Action<float, string> progressDelegate) {
        yield break;
    }
    
    protected override IEnumerator UnloadScene(InitScene scene, Action<float, string> progressDelegate) {
        yield break;
    }
}

public class LoginSceneBase : uFrame.Kernel.Scene {
    
    public override string DefaultKernelScene {
        get {
            return "GodBattleKernelScene";
        }
    }
    
    public virtual LoginSceneSettings Settings {
        get {
            return _SettingsObject as LoginSceneSettings;
        }
        set {
            _SettingsObject = value;
        }
    }
}

public class LoginSceneLoaderBase : SceneLoader<LoginScene> {
    
    protected override IEnumerator LoadScene(LoginScene scene, Action<float, string> progressDelegate) {
        yield break;
    }
    
    protected override IEnumerator UnloadScene(LoginScene scene, Action<float, string> progressDelegate) {
        yield break;
    }
}

public class BattleSceneBase : uFrame.Kernel.Scene {
    
    public override string DefaultKernelScene {
        get {
            return "GodBattleKernelScene";
        }
    }
    
    public virtual BattleSceneSettings Settings {
        get {
            return _SettingsObject as BattleSceneSettings;
        }
        set {
            _SettingsObject = value;
        }
    }
}

public class BattleSceneLoaderBase : SceneLoader<BattleScene> {
    
    protected override IEnumerator LoadScene(BattleScene scene, Action<float, string> progressDelegate) {
        yield break;
    }
    
    protected override IEnumerator UnloadScene(BattleScene scene, Action<float, string> progressDelegate) {
        yield break;
    }
}
