// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using uFrame.IOC;
using uFrame.Kernel;
using uFrame.MVVM;


public class InitSystemLoaderBase : uFrame.Kernel.SystemLoader {
    
    private InitController _InitController;
    
    [uFrame.IOC.InjectAttribute()]
    public virtual InitController InitController {
        get {
            if (_InitController==null) {
                _InitController = Container.CreateInstance(typeof(InitController)) as InitController;;
            }
            return _InitController;
        }
        set {
            _InitController = value;
        }
    }
    
    public override void Load() {
        Container.RegisterViewModelManager<InitViewModel>(new ViewModelManager<InitViewModel>());
        Container.RegisterController<InitController>(InitController);
    }
}
